sudo: false

language: node_js

# env:
#   - MOZ_HEADLESS=1

# addons:
#   firefox: latest

script: npm run lint && npm run test-server-open && npm run test-node && npm run test-browser
after_script: npm run test-server-close

node_js:
  - "4"
  - "6"
  - "8"
  - "lts/*"

cache:
  directories:
    - node_modules
    - $HOME/.npm
